name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  JABBA_INDEX: ${{ github.server_url }}/${{ github.repository }}/raw/${{ github.sha }}/index.json

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java:
          - adoptium@8
          - adoptium@11
          - adoptium@17
          - graalvm-ce-java11@22.0
          - graalvm-ce-java17@22.0
          - openj9-java8@0.29
          - openj9-java11@0.29
          - openj9-java17@0.29
          - corretto@8
          - corretto@11
          - corretto@17
    runs-on: ${{ matrix.os }}
    steps:
      - name: Ignore line ending differences in git
        if: contains(runner.os, 'windows')
        shell: bash
        run: git config --global core.autocrlf false

      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Check if the JDK index is up to date
        shell: bash
        run: sbt checkIndex
